# Generated by Django 2.1.1 on 2020-04-06 09:30

import apps.category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='category_img',
            field=models.ImageField(null=True, upload_to=apps.category.models.develop_update_filename, verbose_name='개발분야 이미지'),
        ),
        migrations.AddField(
            model_name='developbig',
            name='maincategory_img',
            field=models.ImageField(null=True, upload_to=apps.category.models.developbig_update_filename, verbose_name='개발대분야 이미지'),
        ),
    ]
