# Generated by Django 2.2.5 on 2020-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='develop',
            name='coin',
            field=models.IntegerField(default=0, null=True, verbose_name='카테고리당 가격'),
        ),
    ]
