# Generated by Django 2.1.1 on 2020-04-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200406_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='develop',
            name='category_img',
        ),
    ]
