# Generated by Django 2.1.1 on 2020-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaotalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakaotalk',
            name='status_code',
            field=models.IntegerField(default=0, verbose_name='메세지 전송결과'),
        ),
    ]
