# Generated by Django 2.1.1 on 2020-04-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaotalk', '0002_auto_20200402_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kakaotalk',
            new_name='Sendkakao',
        ),
    ]
