# Generated by Django 2.1.1 on 2020-03-30 04:43

import apps.project.models
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='제안비용')),
                ('day', models.CharField(blank=True, max_length=256, null=True, verbose_name='제안개발기간')),
                ('expert', models.CharField(blank=True, max_length=256, null=True, verbose_name='전문성 및 경험')),
                ('strategy', models.CharField(blank=True, max_length=256, null=True, verbose_name='제안 전략')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('state', models.IntegerField(choices=[(0, 'NOTSUBMIT'), (1, 'YES'), (2, 'NO')], default=0, verbose_name='미팅 상태')),
                ('active', models.BooleanField(default=False, verbose_name='활성화여부')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='클라이언트')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner', verbose_name='작성 파트너')),
            ],
            options={
                'verbose_name': '     제안서',
                'verbose_name_plural': '     제안서',
            },
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰제품명')),
                ('price', models.IntegerField(default=0, verbose_name='희망비용')),
                ('day', models.IntegerField(default=0, verbose_name='희망프로젝트기간(일)')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='의뢰내용')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.project.models.request_update_filename, verbose_name='의뢰파일')),
            ],
            options={
                'verbose_name': '     공통질문',
                'verbose_name_plural': '     공통질문',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠1')),
                ('content2', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠2')),
                ('content3', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠3')),
                ('content4', models.CharField(blank=True, max_length=256, null=True, verbose_name='컨텐츠4')),
            ],
            options={
                'verbose_name': '     선택질문컨텐츠',
                'verbose_name_plural': '     선택질문컨텐츠',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '     프로젝트',
                'verbose_name_plural': '     프로젝트',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request1', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰필드1')),
                ('request2', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰필드2')),
                ('request3', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰필드3')),
                ('request4', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰필드4')),
                ('request5', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰필드5')),
                ('request6', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰필드6')),
                ('request7', models.TextField(blank=True, verbose_name='의뢰필드7')),
                ('request8', models.TextField(blank=True, verbose_name='의뢰필드8')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='의뢰제품명')),
                ('price', models.IntegerField(default=0, verbose_name='희망비용')),
                ('day', models.IntegerField(default=0, verbose_name='희망프로젝트기간(일)')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='의뢰내용')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.project.models.request_update_filename, verbose_name='의뢰파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('category', models.ManyToManyField(to='category.Develop', verbose_name='의뢰분야')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='작성클라이언트')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Subclass', verbose_name='의뢰제품')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '     요청된 의뢰',
                'verbose_name_plural': '     요청된 의뢰',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='가격 만족도')),
                ('time_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='일정 준수')),
                ('talk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='의사소통')),
                ('expert_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='전문성')),
                ('result_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='결과 만족도')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='리뷰내용')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Client', verbose_name='작성클라이언트')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Partner', verbose_name='파트너')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '리뷰별점',
                'verbose_name_plural': '리뷰별점',
            },
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=256, null=True, verbose_name='선택질문')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Develop', verbose_name='개발분야중분류')),
            ],
            options={
                'verbose_name': '     선택질문',
                'verbose_name_plural': '     선택질문',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Select', verbose_name='선택질문'),
        ),
        migrations.AddField(
            model_name='answer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='프로젝트'),
        ),
    ]
