# Generated by Django 2.2.5 on 2020-03-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='answer',
            name='active',
            field=models.BooleanField(default=False, verbose_name='활성화여부'),
        ),
    ]
