# Generated by Django 2.1.1 on 2020-04-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200414_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_save',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Develop', verbose_name='개발분야'),
        ),
    ]
