# Generated by Django 2.2.5 on 2020-03-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200323_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Subclass', verbose_name='의뢰제품'),
        ),
    ]
