# Generated by Django 2.1.1 on 2020-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200416_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='active',
            field=models.CharField(blank=True, default=False, max_length=256, null=True, verbose_name='활성화'),
        ),
    ]
