# Generated by Django 2.1.1 on 2020-04-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200420_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='request',
            new_name='select',
        ),
    ]
