# Generated by Django 2.1.1 on 2020-04-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200420_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='select',
            new_name='request',
        ),
    ]
