# Generated by Django 2.1.1 on 2020-04-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200420_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='day',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='희망프로젝트기간(일)'),
        ),
        migrations.AlterField(
            model_name='common',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='희망비용'),
        ),
    ]
