# Generated by Django 2.1.1 on 2020-05-07 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200506_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.AddField(
            model_name='review',
            name='content_bad',
            field=models.TextField(blank=True, null=True, verbose_name='아쉬웠던 점'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_good',
            field=models.TextField(blank=True, null=True, verbose_name='좋았던 점'),
        ),
        migrations.AlterField(
            model_name='review',
            name='result_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='결과물 및 품질'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='업무속도 및 납기'),
        ),
    ]
