# Generated by Django 2.1.1 on 2020-05-19 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_request_add_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 10, 41, 4, 154732, tzinfo=utc), verbose_name='등록일자'),
        ),
    ]
