# Generated by Django 2.1.1 on 2020-05-22 06:14

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200519_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=apps.project.models.time, verbose_name='등록일자'),
        ),
    ]
