# Generated by Django 2.1.1 on 2020-06-06 10:49

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200525_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.project.models.answer_update_filename, verbose_name='의뢰파일'),
        ),
    ]
