# Generated by Django 2.1.1 on 2020-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='examine',
            field=models.BooleanField(default=False, null=True, verbose_name='검토하기 여부'),
        ),
    ]
