# Generated by Django 2.1.1 on 2020-06-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_request_examine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='day',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='price',
        ),
        migrations.AddField(
            model_name='answer',
            name='all_period',
            field=models.IntegerField(default=0, verbose_name='총 개발 기간'),
        ),
        migrations.AddField(
            model_name='answer',
            name='all_price',
            field=models.IntegerField(default=0, verbose_name='예상 견적'),
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='개발 분야'),
        ),
        migrations.AddField(
            model_name='answer',
            name='day_price',
            field=models.TextField(blank=True, null=True, verbose_name='개발 입률'),
        ),
        migrations.AddField(
            model_name='answer',
            name='people',
            field=models.TextField(blank=True, null=True, verbose_name='개발 투입 인원'),
        ),
        migrations.AddField(
            model_name='answer',
            name='period',
            field=models.TextField(blank=True, null=True, verbose_name='예상 개발 기간'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='strategy',
            field=models.TextField(blank=True, null=True, verbose_name='예상 개발 기능'),
        ),
    ]
