# Generated by Django 2.1.1 on 2020-06-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20200615_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='all_period',
            new_name='day',
        ),
    ]
