# Generated by Django 2.1.1 on 2020-06-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20200615_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='active_save',
            field=models.BooleanField(default=True, null=True, verbose_name='활성 변화 저장'),
        ),
    ]
