# Generated by Django 2.1.1 on 2020-06-18 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_request_active_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='제안서 오픈 시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='send_meeting',
            field=models.BooleanField(default=False, verbose_name='미팅 안내 카톡 전송 여부'),
        ),
    ]
