# Generated by Django 3.0.8 on 2020-07-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20200618_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='open_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='제안서 오픈 시간'),
        ),
    ]
