# Generated by Django 3.0.8 on 2020-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20200716_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='info_check',
            field=models.CharField(blank=True, choices=[(0, '정보 미확인'), (1, '파트너사 정보 확인'), (2, '파트너사 연락')], default=0, max_length=2, null=True, verbose_name='정보확인여부'),
        ),
    ]
