# Generated by Django 3.0.8 on 2020-07-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_answer_info_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='info_check',
            field=models.IntegerField(blank=True, choices=[(0, '정보 미확인'), (1, '파트너사 정보 확인'), (2, '파트너사 연락')], default=0, null=True, verbose_name='정보확인여부'),
        ),
    ]
