# Generated by Django 3.0.8 on 2020-08-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20200727_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='add_meeting',
        ),
        migrations.RemoveField(
            model_name='request',
            name='examine',
        ),
        migrations.AddField(
            model_name='request',
            name='send_information',
            field=models.BooleanField(default=False, null=True, verbose_name='의뢰서 정보 카카오톡 발송 여부'),
        ),
    ]
