# Generated by Django 2.1.1 on 2020-05-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200510_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientclass',
            old_name='payment',
            new_name='end_time',
        ),
    ]
