# Generated by Django 2.1.1 on 2020-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='career',
            field=models.CharField(max_length=256, null=True, verbose_name='설립일'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='employee',
            field=models.CharField(max_length=256, null=True, verbose_name='근로자수'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='revenue',
            field=models.CharField(max_length=256, null=True, verbose_name='매출(백만원)'),
        ),
    ]
