# Generated by Django 2.2.5 on 2020-03-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='category_big',
        ),
        migrations.AlterField(
            model_name='partner',
            name='category_middle',
            field=models.ManyToManyField(related_name='category_middle', to='category.Develop', verbose_name='의뢰가능분야'),
        ),
    ]
