# Generated by Django 2.1.1 on 2020-04-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=256, null=True, verbose_name='전화번호'),
        ),
    ]
