# Generated by Django 2.2.5 on 2020-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200325_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='메인 여부'),
        ),
        migrations.AddField(
            model_name='machine',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='메인 여부'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='메인 여부'),
        ),
        migrations.AddField(
            model_name='process',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='메인 여부'),
        ),
        migrations.AddField(
            model_name='structure',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='메인 여부'),
        ),
    ]
