# Generated by Django 2.1.1 on 2020-03-31 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paylist',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='paylist',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='paylist',
            name='buyer_tel',
        ),
        migrations.AddField(
            model_name='paylist',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='비용'),
        ),
        migrations.AddField(
            model_name='paylist',
            name='coin',
            field=models.IntegerField(default=0, verbose_name='코인'),
        ),
        migrations.AddField(
            model_name='paylist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
