# Generated by Django 2.1.1 on 2020-04-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paylist',
            old_name='name',
            new_name='product_name',
        ),
    ]
