# Generated by Django 2.1.1 on 2020-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200406_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylist',
            name='channel',
            field=models.CharField(default=1, max_length=256, verbose_name='결제환경(웹/모바일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paylist',
            name='pay_method',
            field=models.CharField(default=1, max_length=256, verbose_name='결제 방법(카드/휴대폰 등)'),
            preserve_default=False,
        ),
    ]
