# Generated by Django 2.1.1 on 2020-04-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200331_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylist',
            name='coin',
            field=models.PositiveIntegerField(default=0, verbose_name='코인'),
        ),
    ]
