# Generated by Django 2.1.1 on 2020-04-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200404_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylist',
            name='buyer_email',
            field=models.CharField(default=1, max_length=256, verbose_name='구매자 이메일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paylist',
            name='buyer_name',
            field=models.CharField(default=1, max_length=256, verbose_name='구매자 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paylist',
            name='buyer_tel',
            field=models.CharField(default=1, max_length=256, verbose_name='구매자 전화번호'),
            preserve_default=False,
        ),
    ]
