# Generated by Django 2.1.1 on 2020-04-04 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_auto_20200404_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=256, verbose_name='결제정보')),
                ('state', models.IntegerField(choices=[(0, '결제 실패'), (1, '결제 성공')], default=0, verbose_name='결제 상태')),
                ('amount', models.IntegerField(default=0, verbose_name='비용')),
                ('coin', models.IntegerField(default=0, verbose_name='코인')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '     결제저장',
                'verbose_name_plural': '     결제저장',
            },
        ),
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pointtransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='PointTransaction',
        ),
    ]
