# Generated by Django 2.1.1 on 2020-04-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200404_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paylist',
            old_name='amount',
            new_name='product_price',
        ),
    ]
